[package]
name = "osdp"
version = "0.2.1"
description = "Pure-Rust, no_std-friendly implementation of the SIA Open Supervised Device Protocol (OSDP) v2.2"
license = "BSD-3-Clause"
homepage = "https://github.com/Quantumlyy/osdp-rs/blob/main/README.md"
documentation = "https://docs.rs/osdp"
repository = "https://github.com/Quantumlyy/osdp-rs/"
edition = "2024"
rust-version = "1.85"
keywords = ["osdp", "access-control", "rs485", "embedded", "no-std"]
categories = ["embedded", "no-std", "network-programming", "parser-implementations"]

[features]
default = ["std", "secure-channel"]
std = ["alloc"]
alloc = []
secure-channel = ["dep:aes", "dep:cbc", "dep:cipher", "dep:subtle"]
embedded-io = ["dep:embedded-io"]
embedded-io-async = ["dep:embedded-io-async"]
defmt = ["dep:defmt"]

[dependencies]
num_enum = { version = "0.7", default-features = false }
bitflags = { version = "2.6", default-features = false }

aes = { version = "0.8", default-features = false, optional = true }
cbc = { version = "0.1", default-features = false, optional = true }
cipher = { version = "0.4", default-features = false, optional = true }
subtle = { version = "2.6", default-features = false, optional = true }

embedded-io = { version = "0.6", optional = true }
embedded-io-async = { version = "0.6", optional = true }
defmt = { version = "0.3", optional = true }

[dev-dependencies]
proptest = "1.5"

[lib]
name = "osdp"
path = "src/lib.rs"
